baseURL = 'https://blog.achirsh.site/'
languageCode = "zh-cn"
title = 'achirsh blog'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true 

[params]
  author = "achirsh"
  description = ""
  github = "achirsh"
  email = ""
  url = "https://blog.achirsh.site"
  keywords = "blog, google analytics"
  lastmod = false
  favicon = "/images/github.png"
  location = "中国"
  userStatusEmoji = ""

  [[params.links]]
    title = "Link"
    href = "https://github.com/achirsh"